delete from addresses;
delete from addresses;
delete from units;
delete from serial_numbers;
delete from product_categories;
delete from ledgers;
delete from ledger_groups;
delete from account_years;
delete from organizations;