###
@host = 127.0.0.1:8080
###

GET http://{{host}}/users

###
GET http://127.0.0.1:8080/users/2

###
POST http://{{host}}/users
Content-Type: application/json

{
    "name": "Administrators",
    "is_enabled": true
}

###
PUT http://{{host}}/users/1
Content-Type: application/json

{
    "name": "Administrators",
    "is_enabled": true   
}

###

DELETE http://{{host}}/users/1
